"""Round-trip smoke test for the NumCalc BEMBackend adapter (build-order item 3).

Feeds normalized core-type inputs through the full interface (prepare → solve → extract)
using the real NumCalc binary on a pulsating-sphere mesh at two frequencies, and asserts
the returned ComplexField has the correct shape, dtype, finite non-zero pressures, and
convergence flags.

Test geometry (chosen so item 4 can validate against the exact analytic solution):
  - Pulsating sphere, radius a = 0.10 m, centered at the global coordinate origin.
  - Boundary: icosphere subdivision 1 (~80 triangles), all elements vibrating at unit
    normal velocity (uniform complex scalar 1+0j), a single group tag (1).
  - Frequencies: [250, 500] Hz (ka ≈ 0.46, 0.92).
  - Observation: Lebedev N=14 at r = 1.0 m.
  - Solver: conventional collocation BEM (method 0), no Burton–Miller (simple geometry).

The mesh is NOT throwaway. Item 4 reuses it for V-1 (analytic piston / pulsating sphere
validation), so geometry, winding, and phase must be physically correct now.

Marker: local_only — this test requires the NumCalc binary. It is skipped automatically
when BEAMSIM2_NUMCALC_BIN is unset, keeping 'uv run pytest' (without the binary) green.
"""

from __future__ import annotations

import math
import os

import numpy as np
import pytest

from beamsim2.core.sphere import lebedev
from beamsim2.core.types import BoundaryConditions, FrequencyGrid, Mesh, SolverConfig

# ── Resolve the binary once at collection time and skip if absent ─────────────

try:
    from beamsim2.backends.numcalc.config import resolve_numcalc_binary

    _BINARY = resolve_numcalc_binary()
except FileNotFoundError:
    _BINARY = None

pytestmark = pytest.mark.local_only


def _skip_if_no_binary() -> None:
    if _BINARY is None:
        pytest.skip("NumCalc binary not found. Set BEAMSIM2_NUMCALC_BIN to run this test.")


# ---------------------------------------------------------------------------
# Pulsating-sphere mesh builder
# ---------------------------------------------------------------------------


def _pulsating_sphere_mesh(radius: float, subdivisions: int) -> Mesh:
    """Build an icosphere mesh centered at the origin with consistent outward normals.

    In acoustics terms: this is a rigid piston boundary that vibrates radially
    with uniform velocity — the exact geometry of a monopole/pulsating sphere.

    The mesh is generated by recursive subdivision of a regular icosahedron.
    All vertex positions are normalized to radius r, giving a surface mesh that
    converges to a sphere. Winding is set so the outward normal (computed as the
    cross-product of two triangle edges) points away from the origin — required for
    a sign-correct VELO boundary condition in NumCalc.

    Parameters
    ----------
    radius : float
        Sphere radius in metres.
    subdivisions : int
        Number of midpoint-subdivision iterations.
        0 → 20 triangles (icosahedron), 1 → 80, 2 → 320, 3 → 1280.

    Returns
    -------
    Mesh
        vertices [V, 3] float64, triangles [T, 3] int32, group_tags [T] int32 = 1.
        All triangles in group 1 (one vibrating group, sound-hard = none).
    """
    # ── Icosahedron base vertices ────────────────────────────────────────────
    phi = (1.0 + math.sqrt(5.0)) / 2.0  # golden ratio ≈ 1.618
    # 12 vertices; normalize to unit sphere
    raw_verts = np.array(
        [
            [-1, phi, 0],
            [1, phi, 0],
            [-1, -phi, 0],
            [1, -phi, 0],
            [0, -1, phi],
            [0, 1, phi],
            [0, -1, -phi],
            [0, 1, -phi],
            [phi, 0, -1],
            [phi, 0, 1],
            [-phi, 0, -1],
            [-phi, 0, 1],
        ],
        dtype=np.float64,
    )
    raw_verts /= np.linalg.norm(raw_verts, axis=1, keepdims=True)

    # ── Icosahedron faces (CCW viewed from outside) ──────────────────────────
    raw_faces = np.array(
        [
            [0, 11, 5],
            [0, 5, 1],
            [0, 1, 7],
            [0, 7, 10],
            [0, 10, 11],
            [1, 5, 9],
            [5, 11, 4],
            [11, 10, 2],
            [10, 7, 6],
            [7, 1, 8],
            [3, 9, 4],
            [3, 4, 2],
            [3, 2, 6],
            [3, 6, 8],
            [3, 8, 9],
            [4, 9, 5],
            [2, 4, 11],
            [6, 2, 10],
            [8, 6, 7],
            [9, 8, 1],
        ],
        dtype=np.int32,
    )

    verts = raw_verts
    faces = raw_faces

    # ── Midpoint subdivision ─────────────────────────────────────────────────
    for _ in range(subdivisions):
        verts, faces = _subdivide(verts, faces)

    # Scale to requested radius.
    verts = verts * radius

    # ── Verify outward normals ───────────────────────────────────────────────
    # For each triangle, the centroid should be in the same half-space as the normal.
    # If not, flip the winding.
    v0 = verts[faces[:, 0]]  # [T, 3]
    v1 = verts[faces[:, 1]]  # [T, 3]
    v2 = verts[faces[:, 2]]  # [T, 3]
    normals = np.cross(v1 - v0, v2 - v0)  # [T, 3] — not normalized
    centroids = (v0 + v1 + v2) / 3.0  # [T, 3]
    # Dot centroid with normal: positive → outward, negative → flip.
    dots = np.einsum("ij,ij->i", normals, centroids)  # [T]
    inward_mask = dots < 0
    if inward_mask.any():
        # Swap columns 1 and 2 on inward-facing triangles to flip winding.
        faces[inward_mask] = faces[inward_mask][:, [0, 2, 1]]

    group_tags = np.ones(len(faces), dtype=np.int32)  # [T] — all group 1

    return Mesh(
        vertices=verts.astype(np.float64),
        triangles=faces.astype(np.int32),
        group_tags=group_tags,
    )


def _subdivide(verts: np.ndarray, faces: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """One iteration of midpoint subdivision on a sphere.

    Splits each triangle into 4 by inserting edge midpoints, normalized back
    to the unit sphere.

    Parameters
    ----------
    verts : np.ndarray, shape [V, 3] float64
    faces : np.ndarray, shape [T, 3] int32

    Returns
    -------
    tuple[np.ndarray, np.ndarray]
        New (verts, faces) arrays after subdivision.
    """
    edge_midpoints: dict[tuple[int, int], int] = {}
    new_verts = list(verts)

    def midpoint(a: int, b: int) -> int:
        key = (min(a, b), max(a, b))
        if key not in edge_midpoints:
            mid = (new_verts[a] + new_verts[b]) / 2.0
            mid /= np.linalg.norm(mid)  # project back to unit sphere
            edge_midpoints[key] = len(new_verts)
            new_verts.append(mid)
        return edge_midpoints[key]

    new_faces: list[list[int]] = []
    for a, b, c in faces:
        ab = midpoint(a, b)
        bc = midpoint(b, c)
        ca = midpoint(c, a)
        new_faces.extend([[a, ab, ca], [b, bc, ab], [c, ca, bc], [ab, bc, ca]])

    return np.array(new_verts, dtype=np.float64), np.array(new_faces, dtype=np.int32)


# ---------------------------------------------------------------------------
# Round-trip smoke test
# ---------------------------------------------------------------------------


def test_numcalc_roundtrip() -> None:
    """Prove that normalized inputs round-trip through the NumCalc adapter.

    Checks shape, dtype, finiteness, non-zero magnitude, convergence flags,
    and frequency echo. Does NOT check phase or SPL accuracy — that is item 4.
    """
    _skip_if_no_binary()

    from beamsim2.backends.numcalc.adapter import NumCalcBackend

    # ── Inputs ───────────────────────────────────────────────────────────────
    sphere_mesh = _pulsating_sphere_mesh(radius=0.10, subdivisions=1)
    # ~80 triangles, all in group 1, uniform unit velocity
    bc = BoundaryConditions(vibrating_groups={1: complex(1.0, 0.0)})
    freqs = FrequencyGrid(
        frequencies=np.array([250.0, 500.0], dtype=np.float64),
        spacing="linear",
        fractional_octave=None,
    )
    obs = lebedev(n_points=14, radius=1.0)  # 14-point Lebedev at 1 m
    config = SolverConfig(
        n_epw=6,
        tolerance=1e-6,
        max_iterations=1000,
        burton_miller=False,  # simple geometry; BM not needed for smoke test
        speed_of_sound=343.2,
        air_density=1.2041,
    )

    backend = NumCalcBackend()

    # ── prepare ───────────────────────────────────────────────────────────────
    spec = backend.prepare(sphere_mesh, bc, freqs, obs, config)

    assert os.path.isfile(spec.nc_inp_paths[0]), "NC.inp was not written"
    assert os.path.isdir(os.path.join(spec.work_dir, "ObjectMesh")), "ObjectMesh/ missing"
    assert os.path.isdir(os.path.join(spec.work_dir, "EvalGrid")), "EvalGrid/ missing"
    assert spec.frequency_grid is freqs

    # ── solve ─────────────────────────────────────────────────────────────────
    raw = backend.solve(spec)

    assert raw.work_dir == spec.work_dir
    assert len(raw.completed_steps) == 2, f"Expected 2 completed steps, got {raw.completed_steps}"
    assert raw.convergence_flags.shape == (2,), "convergence_flags shape wrong"

    # ── extract ───────────────────────────────────────────────────────────────
    field = backend.extract(raw, obs)

    # ── Shape and dtype ───────────────────────────────────────────────────────
    assert field.pressure.shape == (
        2,
        14,
    ), f"Expected pressure shape (2, 14), got {field.pressure.shape}"
    assert field.pressure.dtype == np.complex128, f"Expected complex128, got {field.pressure.dtype}"
    assert field.convergence_flags.shape == (2,)
    assert field.frequencies.shape == (2,)

    # ── Physical sanity ───────────────────────────────────────────────────────
    assert np.all(np.isfinite(field.pressure)), "pressure contains non-finite values"
    assert np.all(np.abs(field.pressure) > 0), "pressure magnitude is zero"

    # ── Convergence ───────────────────────────────────────────────────────────
    assert field.convergence_flags.all(), (
        "CGS solver did not converge at all steps. " f"Flags: {field.convergence_flags}"
    )

    # ── Frequency echo ────────────────────────────────────────────────────────
    np.testing.assert_array_equal(field.frequencies, [250.0, 500.0])

    print(
        f"\nRound-trip passed:\n"
        f"  pressure shape : {field.pressure.shape}  dtype={field.pressure.dtype}\n"
        f"  |p| range      : {np.abs(field.pressure).min():.4e} … "
        f"{np.abs(field.pressure).max():.4e}  Pa\n"
        f"  converged      : {field.convergence_flags.tolist()}\n"
        f"  work_dir       : {spec.work_dir}"
    )
